#pragma once
#define ATTRIBUTESIZE 8

#define ATTRIBUTESIZE_VERTEX 3
#define ATTRIBUTESIZE_UV 2
#define ATTRIBUTESIZE_NORAML 3

#define ATTRIBUTEINDEX_VERTEX 0
#define ATTRIBUTEINDEX_UV 1
#define ATTRIBUTEINDEX_NORAML 2

#define ATTRIBUTE_OFFSET_VERTEX 0
#define ATTRIBUTE_OFFSET_UV 3
#define ATTRIBUTE_OFFSET_NORMAL 5